---
- name: Install Memcached and Python Memcache library
  become: true
  apt:
    name:
      - memcached
      - python3-memcache
    state: latest

- name: Configure Memcached
  become: true
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^(-l\s+)'
    line: '\g<1>192.168.56.114'
  notify: restart memcached
